### ISSUE TITLE
About training dataset and get the .hdr image

### ISSUE THREAD

**Issue by tyc97-sys** [wanghu178/KUNet#2]
Thanks for your work, and your reply for the last issue.
I have some questions about training dataset and geting the .hdr image.
Could I train it on 32-bit HDR image? I trained it on dataset "HDR-Real" and "HDR_Synth."
And could I just using `cv2.imwrite('hdr_img_path.hdr', sr_img)` to get the HDR image? It seems there are some problem when I using this function.
How can I get the `.hdr` image when I using this work?

Thank you~

**Comment by wanghu178** [comment]
The *.hdr format is stored as a float  type. KUNet does not take 32bit images into account, you can try to see if KUNet can solve the problem. If I remember correctly those two datasets read out float type, the numbers you print out directly are very small. 

The function *.hdr format read by opencv is a float type. In fact *.hdr format files are in RGBE format. It is recommended to rewrite a function for storing *.hdr format files.

Best wishes！
