### ISSUE TITLE
where is the "./scripts/extract_subimgs_single.py" file?

### ISSUE THREAD

**Issue by EEWenbinWu** [wanghu178/KUNet#3]

**Comment by wanghu178** [comment]
非常感谢您的提醒，我们是用HDRTVNet的方法进行抽取子图像的。 为了方便大家复现该模型，我刚刚上传了抽取方法（需要注意的是，该抽取方案是HDRTVNet的工作，不是我们的）
再一次感谢您对我们工作的关注，感谢！

**Comment by EEWenbinWu** [comment]
谢谢。不过这个代码我看过，好像没有处理gt的哦

**Comment by EEWenbinWu** [comment]
我就是想看看gt是怎么处理的，但是好像没有找到

**Comment by wanghu178** [comment]
如果您使用的是HDRTV数据集，要是我理解没有问题的话，抽取方式应该是一致的。代码里面是cv2.IMREAD_UNCHANGED。

**Comment by EEWenbinWu** [comment]
HDRTV数据集的hdr图片是什么格式的呢，hdr后缀的吗，还是像ntire一样带一个npy

**Comment by wanghu178** [comment]
哦哦我明白了，你想搞乃个NTIRE的数据集。这个数据集要加一个东西， 我给你找一下，好几个月前的我希望我能找到，找到后我上传到上面去。

**Comment by EEWenbinWu** [comment]
好的，感谢。不过我自己的数据是hdr格式的，按道理直接用cv2.IMREAD_UNCHANGED是可以的

**Comment by wanghu178** [comment]
不好意思，我刚刚没找到。等我有时间了在写一个传上去。按道理应该可以我记得singleHDR就是这样搞得 或者flags = cv2.IMREAD_ANYDEPTH也可以。你注意一下读取的数据是不是原始数据。RGBE格式的数据貌似要转换。我好早之前用过但是忘记了。我记得HDR格式提出的时候有一个C的代码，里面详细解释了该格式你可以查一下
